apps/friends/urls.py
from django.conf.urls import url
##from django.contrib import admin
from . import views

urlpatterns = [
  url(r'^$', views.main, name='index'),
  url(r'^friends$', views.success, name='success'),
  url(r'^user/(?P<id>\d+)$', views.profile, name='profile'),
  url(r'^register$', views.register, name='register'),
  url(r'^login$', views.login, name='login'),
  url(r'^logout$', views.logout, name='logout'),
  url(r'^remove/(?P<id>\d+)$', views.remove, name='remove'),
  url(r'^add/(?P<id>\d+)$', views.add, name='add'),
    # url(r'^this_app/(?P<id>\d+)/edit$', views.edit, name='my_edit'),
    # url(r'^this_app/(?P<id>\d+)/delete$', views.delete, name='my_delete'),
    # url(r'^this_app/(?P<id>\d+)$', views.show, name='my_show'),
]

main/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include ### ADDED THIS LINE (used below)


urlpatterns = [
    url(r'^', include('apps.friends.urls', namespace = 'friends')),
    url(r'^admin/', admin.site.urls),
]

apps/friends/models.py
#-*- coding: utf-8 -*-
# Python Tuples are Not Just Constant Lists
# () is a tuple: An immutable collection of values, usually (but not necessarily) of different types.
# [] is a list: A mutable collection of values, usually (but not necessarily) of the same type.
# {} is a dict: Use a dictionary for key value pairs.
# For the difference between lists and tuples see here. See also:

from __future__ import unicode_literals
from django.db import models
from datetime import datetime, date
import re
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+.[a-zA-Z]+$')
NAME_REGEX = re.compile(r'^([a-zA-Z][a-zA-Z ]+[a-zA-Z])$') #assumes at least 2 strings 
#NAME_REGEX = re.compile(r'^[a-zA-Z]+$') 
#PSWD_REGEX = re.compile(r'^(?=.?\d)(?=.?[A-Z])(?=.?[a-z])(?=.[$@$!%?&])[A-Za-z\d$@$!%?&]{8,}$')

#No methods in our new manager should ever catch the whole request object!!! 
# (Just parts, ex. request.POST)
class UserManager(models.Manager):
# unpacking of postData is via a * (i.e. star) if postData is a list, and ** (i.e. kwargs) if
# postData is a dictionary. Ex: def validate_user(self, **postData)
        def validate_user(self, postData):
                response_to_views = {}
                errors = {}
                # errors=[]

                print "****************In UserManager: validate_user method*****************"
                print postData
                #Validations example: error["desc"] = "Blog desc should be more than 10 characters" if using error tags.
                print postData['reg_email']
                reg_email = postData['reg_email'].strip(' \t\n\r')
                reg_email=reg_email.lower()
                # name= postData['name'].strip(' \t\n\r')
                if not postData['name']:
                        # errors.append("Name is required!")
                        errors["name"]="Name is required!"
                elif not NAME_REGEX.match(postData['name']):
                        errors["name"]="Your entered Name has either leading whitespace, numeric or special characters. \nOnly alphabetic characters and spaces are allowed in the Name field."                
                if not postData['alias']:
                        errors["alias"]="Alias is required!"                
                if not postData['reg_email']:
                        errors["reg_email"]="Email is absolutely required!"
                elif not EMAIL_REGEX.match(reg_email):
                        errors["reg_email"]="Email format is incorrect. Please re-enter."
                if self.filter(email=reg_email):
                        errors["reg_email"]="There is a already a user registered with this email.\n Might you want to login instead? :)"
                if len(postData['reg_pwd'])<8:
                        errors["reg_pwd"] ="Password must be at least 8 chars long!"
                if not postData['conf_pwd']:
                        errors["conf_pwd"] = "Please confirm your password!"
                if not postData['reg_pwd'] == postData['conf_pwd']:
                        if errors["conf_pwd"]:
                                errors["conf_pwd"] = errors["conf_pwd"] + "Form passwords must match!"
                        else:
                                errors["conf_pwd"]="Form passwords must match!"
                print postData['dob']
                if not postData['dob']:
                        errors["dob"] ="You have to select a birthdate."
                if not postData['dob'] < unicode(date.today()):
                        errors["dob"] ="You could not possibly be born in the future :D!?"
                #check the errors [] or errors{} for failed validations:
                if errors:
                        response_to_views['status']= False
                        response_to_views['errors']= errors
                        print ("post validations in the if_errors statement, and printing the recorded errors: ", response_to_views['errors'])
                else:
                        response_to_views['status']= True
                        h_reg_pwd = bcrypt.hashpw(postData['reg_pwd'].encode("utf-8"), bcrypt.gensalt())
                        response_to_views['user']=self.create(name=postData['name'], alias=postData['alias'], email=postData['reg_email'].lower(), password=h_reg_pwd, dob=postData['dob'])
                return response_to_views

        def validate_login(self, postData):
        # So now the request.POST (a dict type object) 
        # can be accessed like this:
        # postData['form_field'] or postData['password'] etc..
        # .get gets 1 back (an actual object)
        # .get freaks out if 1) you get more than one
        # AND if 2) you get 0.  LOL!!
        # .find returns a list! So does .filter! :)
        # Can do this:
        # user = self.find(email=postData['email'])
        # BUT NOT: user = User.find(email=postData['email'])  ( UserManager class which 
        # inherits from "models.Manager" does not have any reference or knowledge of User class outside of the 'self' object!)
        # ...and an empty or non-empty list sent back to us as result.
        
                print "************************* in login_validation Manager method*************************"
                response_to_views= {} #as a dictionary
                # the .get() method would give us an error if the email does not exist in the User table!
                # so we user .filter(), like " usr = self.filter(email = postData['l_email']) "
                
                l_email = postData['l_email'].strip(' \t\n\r')
                l_email = l_email.lower()
                u = self.filter(email=l_email)
                # u = self.filter(email = postData['l_email'].lower()) 
                print ("Shown object, if found user with this email: ", u)
                
                if u:
                        print "this is the original field: " + postData['l_email']
                        print "this is the stripped email: "+ l_email  
                        print postData['l_pwd']
                        stored_hash = u[0].password
                        print ("this is the hashed pwd in db: " + stored_hash)
                        if not bcrypt.checkpw(postData['l_pwd'].encode("utf-8"), stored_hash.encode("utf-8")):
                        # could also encrypt same and compare:
                        # input_hash = bcrypt.hashpw(postData['l_pwd'].encode("utf-8"), bcrypt.gensalt())
                        # if not input_hash == stored_hash:
                                response_to_views['status']=False
                                response_to_views['error']="Invalid Password on Login. Please try again."
                        else:
                                response_to_views['status']=True
                                response_to_views['user']=u[0]
                else: #invalid email
                        response_to_views["status"]=False
                        response_to_views['error']="Login E-mail is not recognized. Please re-enter."
                return response_to_views

# Create your models here.
class User(models.Model):
        # Django has pre-built validations, such as specifying a field to
        # be unique. Ex: name = models.CharField(max_length = 255, uniquefield)
        name = models.CharField(max_length=255)
        alias = models.CharField(max_length=255)
        email = models.CharField(max_length=255)
        # btw SQLite has also a special:
        # email = models.EmailField()
        # instead of the regex formatting, can use this for properly 
        # formatted emails!
        password = models.CharField(max_length=255)
        dob = models.DateField()
        friends = models.ManyToManyField("self")
        created_at = models.DateTimeField(auto_now_add = True)
        updated_at = models.DateTimeField(auto_now = True)
        objects = UserManager() # (only needed if you need custom model methods such as validations)
        def __repr__(self):
                return "<User object:   Name: {}, Alias: {}, Email: {}, \n Password: {} DOB: {}, Created: {}, Updated: {}, \n Friends: {}>".format(self.name, self.alias, self.email, self.password, self.dob, self.created_at, self.updated_at, self.friends)
        
        # DEBUGGING:
        # If you have this unicode code in place, then when you print an object in the terminal, 
        # it will display with the information
        # you have specified (useful for debugging)
        #     def __unicode__(self):
        #             return "id: " + str(self.id) + ", email: " + self.email 
        # We could also create __str__ or __repr__ method in the class to handle how we want the objects to print =) !!
  

apps/friends/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from .models import User, UserManager
from django.contrib import messages
from django.shortcuts import get_list_or_404, get_object_or_404
from checkuser import *

# Create your views here.
def main(request):   
    #@ensure_current_user
        # cannot do (if request.session["user_id"]) because python is unforgiving!
    if "user_id" in request.session:
        return redirect('friends:success')
    else: 
            #context={"my_message" : "Hello, I am your successesful login/registration request"}
        return render(request, 'friends/main.html')
         
def register(request):
    if request.method=='POST':
        print['****************in view method****************']
        print[request.POST]
        response_from_models = User.objects.validate_user(request.POST)
        print['****************back in view method****************']

        #on successful reg validation
        if response_from_models['status']:
            request.session['user_id']= response_from_models['user'].id
            return redirect('/friends')   
        #else return redirect ('/')
        else:
            #HOW MESSAGES WORK/PASSED BACK TO CLIENT:
            # The 'messages' object's methods also require the 'request'
            # object to be passed as a first parameter...
            # These messages are then going to be inside of that 'request' 
            # object to pass them back.

            # If errors in response_from_models is not a dictionary, but a list/array:
            # for error in response_from_models['errors']:
            #     messages.error(request, error)            

            # If errors in response_from_models IS a dictionary of tags and error messages:
            for tag, error in response_from_models['errors'].items():
                print tag, error
                messages.error(request, error, extra_tags=tag)
            return redirect('/')    
    else:
        # not a post, redirect to index method?
        return redirect('/') #our main.html template
    
def login(request):
    if request.method=='POST':
        print['****************in view method****************']
        print[request.POST]
        #invoke my method from the User model manager
        response_from_models = User.objects.validate_login(request.POST)
        print "************************* in login view method*************************"
        print response_from_models
        if response_from_models["status"]:
            request.session["user_id"]=response_from_models['user'].id
            #on successful login validation
            return redirect('/friends')
        else:
            #use the error message to display; will be just one string, so no need to loop through.
            messages.error(request, response_from_models['error'])
            return redirect('/')
    else:
        # not a post, redirect to index method?
        return redirect('friends:index') #our main.html template

def success(request):
    if "user_id" in request.session:
        print "************************* in login view method*************************"
        # context={"success_str" : "Hello, I am your successesful login/registration request"}
        print "user id of the logged in user is: ", request.session["user_id"]
        # me_id=User.objects.filter(id=request.session["user_id"]).values_list(flat=True)
        # friends_ids=User.objects.get(id=request.session["user_id"]).friends.all().values_list(flat=True)
        # all_users_ids=User.objects.all().values_list(flat=True)
        # not_friends_ids=all_users_ids.difference(me_id, friends_ids)

        me=User.objects.filter(id=request.session["user_id"])
        friends=User.objects.get(id=request.session["user_id"]).friends.all()
        all_users=User.objects.all()
        not_friends=all_users.difference(me, friends)
        print not_friends
        # <!-- Setting Relationships:
        # Comment.objects.create(blog=Blog.objects.get(id=1), comment="test") - create a new comment where the comment's blog points to Blog.objects.get(id=1). -->
        # Blog.objects.raw("SELECT * FROM {{app_name}}_{{class/table name}}") - performs a raw SQL query
        context = {
            'not_friends': not_friends,
            'friends' : friends,
            'me' : me[0]
        }
        return render(request, 'friends/friends.html', context)
    else:
        print request.session
        request.session.clear()
        return redirect ('/')

def profile(request, id):
    if "user_id" in request.session:
        print "*******************in Profile View**********************"
        user=User.objects.filter(id=id)
        if user:
            print "filter result: ", user
            print "user result: ", user[0]
        
            #pull up the info page on the provided user "id"
            return render(request, 'friends/profile.html', {"user":user[0]})
        else:
            print "Profile method decided there is no such ID in User table"
            return redirect('friends:success')
        return redirect('friends:index')
    else:
        return redirect('friends:logout')
        

def remove(request, id):
    print "Someone just called the 'remove' method"
    friend=get_object_or_404(User, id=id)
    # friend=User.objects.get(id=id)
    logged_user=User.objects.get(id=request.session["user_id"])
    #same for "this_user2
    rem_result=logged_user.friends.remove(friend)
    print rem_result
    #Need to clear that cookie/session dictionary/table =) !
    return redirect('friends:success' )
    
def add(request, id):
    print "Someone just called the 'add' method"
    to_friend=get_object_or_404(User, id=id)
    # to_friend=User.objects.get(id=id)
    logged_user=User.objects.get(id=request.session["user_id"])
    add_result=logged_user.friends.add(to_friend)
    print add_result
    return redirect('friends:success')

def logout(request):
    print "Someome just called the 'logout' method "
    #Need to clear that cookie/session dictionary/table =) !
    request.session.clear()
    return redirect('friends:index')

apps/friends/templates/friends/friends.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">    
        <title>Friends </title>
        <!-- ADDED THIS TO LOAD STATIC FOLDER ITEMS -->
        {% load static %}
        <!-- <link rel="stylesheet" href="{% static 'friends/css/style.css' %}"> -->
    </head>

    <body>
        {% if error_message %}
            <p><strong> {{ error_message }}</strong></p>
        {% endif %}
        <!-- Grab user "alias" -->
        <span><h3>Hello, {{me.alias}} </h3></span>
        <a href="{% url 'friends:logout' %}">Logout</a>

        <p>Here is the list of your friends: </p>
        <table>
            <colgroup>
                <col>
                <col style="background-color: rgb(100, 128, 0)">
            </colgroup>
            <tr>
                <th>Alias</th>
                <th>Action</th>
            </tr>
            {% if friends %}
                {% for friend in friends %}
                    <tr>
                        <td> {{friend.alias}} </td>
                        <td> 
                            <a href="{% url 'friends:remove' id=friend.id %}">Remove as friend</a>
                            <a href="{% url 'friends:profile' id=friend.id %}">View Profile</a>
                        </td>
                    </tr>
                {% endfor %}
                </table>            
            {% else %}
                </table>
                <p>You do not have any friends yet. C'mon, add some friends to your profile!</p>
            {% endif %}

        <p>Other Users not on your friend's list:</p>
        <!-- Table of Alias(Link: View Profile) and Action (Link: Add as Friend) -->
        <table>
            <colgroup>
                <col>
                <col style="background-color: rgba(185, 155, 73, 0.486)">
            </colgroup>
            <tr>
                <th>Alias</th>
                <th>Action</th>
            </tr>
            {% if not_friends %}
                {% for user in not_friends %}
                    <tr>    
                        <td><a href="{% url 'friends:profile' id=user.id %}">{{user.alias}}</a></td>
                        <td><a href="{% url 'friends:add' id=user.id %}">Add as Friend</a></td>
                    </tr>
                {% endfor %}
                </table>            
            {% else %}
                </table>
                <p>There are currently no more users to add as your friends. Invite more users to the platform to friend them!</p>
            {% endif %}
    </body>
</html>

apps/friends/templates/friends/main.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">    
        <title> Login / Registration</title>
        <!-- ADDED THIS TO LOAD STATIC FOLDER ITEMS -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'friends/css/style.css' %}">
    </head>

    <body>
        <div id="wrapper">
            <h1>Welcome!</h1>

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if messages.tags %} value = "{{message.tags}}" {% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <form class="register" action="{%url 'friends:register' %}" method="post">
                {% csrf_token %}
                Register
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" value="">
                <label for="alias">Alias:</label>
                <input type="text" id="alias" name="alias" value="">
                <label for="reg_email">Email:</label>
                <input type="text" id="reg_email" name="reg_email" value="">
                <label for="reg_pwd">Password:</label> 
                <input type="password" id="reg_pwd" name="reg_pwd" value="">
                <span>*Password should be at least 8 characters</span>
                <label for="conf_pwd">Confirm PW:</label> 
                <input type="password" id="conf_pwd" name="conf_pwd" value="">
                <label for="dob">Date of Birth:</label> 
                <input type="date" id="dob" name="dob" value="">
                <input type="submit" name="register" value="Register">
            </form> 

            <!-- can use the input type="email" above, part of HTML5,
            which does ALL of the validations for you. But you will never even
            get to the self-created validations in the model.Manager ;( -->

            <!-- !!!!!!!!!!!ROUTING!!!!!!!!!!!!!!!! 
            1) The leading "/" in the action="/your_route" tells the server to go back to 
            localhost root (home). 
            2) So starting from the root of project, matches the r'^' and routes to the
            appropriate app urls file.
            3) Where it hopefully :) finds it's match, i.e. "your_route"! -->

            <form class="login" action="/login" method="post">
                {% csrf_token %}
                Login
                <label for="l_email">Email:</label>
                <input type="text" id="l_email" name="l_email" value="">
                <label for="l_pwd">Password:</label>
                <input type="password" id="l_pwd" name="l_pwd" value="">
                <input type="submit" name="login" value="Login">
            </form>
        </div>
    </body>
</html>

apps/friends/templates/friends/profile.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title> {{user.alias}}</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'friends/css/style.css' %}">
    </head>
    <body>
        <a href="{% url 'friends:success' %}">Home</a>
        <a href="{% url 'friends:logout' %}">Logout</a>
        <h3>{{user.alias}}'s Profile</h3>
        <p>Name: {{user.name}}</p>
        <p>Email Address: {{user.email}}</p>
    </body>
</html>